gfx/env/sky_fppbk.tga
gfx/env/sky_fppdn.tga
gfx/env/sky_fppft.tga
gfx/env/sky_fpplf.tga
gfx/env/sky_fpprt.tga
gfx/env/sky_fppup.tga
models/bed_metal_old.mdl
models/bltree1.mdl
models/factory_forklift.mdl
models/furniture_group-hotel01.mdl
models/generatortrailer01.mdl
models/lantern.mdl
models/record_player.mdl
models/wooden_chair.mdl
models/xen_stamm.mdl
models/pi_tree2.mdl
sound/ambience/28days.wav
sound/ambience/birdy1.wav
sound/ambience/fall_into_water.wav
sound/ambience/generator.wav
sound/ambience/industrial_machine.wav
sound/ambience/lake_water.wav
sound/ambience/lavamud.wav
sound/ambience/Lornaderek.wav
sound/ambience/lucid_bass.wav
sound/ambience/miserere.wav
sound/ambience/record_end.wav
sound/ambience/rope_stretch2.wav
sound/ambience/smallgust2.wav
sound/ambience/smells_like_content.wav
sound/ambience/the_sunlight.wav
sound/ambience/tree_room.wav
sound/ambience/tunnel_wind_loop.wav
sound/ambience/whoosh.wav
sound/ambience/wind_se.wav
sound/ambience/wind_tunnel1.wav
sprites/glow02.spr
sprites/laserbeam.spr
